### PR TITLE
Initial commit for git-diff.md

### PR DESCRIPTION
**Pull request by MMChandler**
I have written a clear, easy-to-comprehend details for `git diff`. I believe this explanation, free of complex technical terms, will swiftly and thoroughly inform anyone about the use-cases, merit, and advantages, of `git diff`. Seasoned developers, new programmers, and even amateur users new to git will benefit from the clear language, exposing the usage of the command to a broader range of users.

### CODE REVIEW

**Comment by NathanJPlummer** [comment]
@MMChandler 

Fantastic work!  Only thing I would suggest is a small blurb explaining how to set up using a GUI diff program in git.

**Comment by MMChandler** [comment]
@NathanJPlummer Thanks for the feedback! Got a small section added for `git difftool`.

**Comment by NathanJPlummer** [comment]
@MMChandler 

I'm always impressed with the speed with which you respond.  Great work!  👍

**Comment by MMChandler** [comment]
Thanks!

Michael M. Chandler
808-640-8033
michael.m.chandler@icloud.com

**Pull request merged**
