### PR TITLE
git-add.md

### PR DESCRIPTION
**Pull request by plosty**
I have written a clear, easy-to-comprehend details for git-add. 

I believe this explanation, free of complex technical terms, will swiftly and thoroughly inform anyone about the use-cases, merit, and advantages, of git-add. 

Seasoned developers, new programmers, and even amateur users new to git will benefit from the clear language, exposing the usage of the command to a broader range of users.

### CODE REVIEW

**Comment by aashishnagpal** [comment]
@plosty Thank you for your submission. We appreciate you stepping up and taking `git add` to explain to the masses.

Your submission is okay. Below are a few points to consider for improvement, to take it to another level.

Firstly, you should always keep in mind that when writing an article such as this, where you are explaining a concept, you are really reaching out to a very broad range of audience. The reader could be an intermediate git user trying to understand what `git add` is or it could be even a beginner who does not understand `git` at all. So your article should be able to cater to this broad range by being more comprehensive and having a better explanation.

Right now your article seems to assume that the reader would have some basic knowledge of what `git` is and what some of the related terms could be. The article should not expect that.

I would suggest you add a little bit of background to the Overview section to illustrate what `git add` is and what's its purpose. And then detail it out in the Description section.

> unstaged file (not tracked) -> add file to staging area -> commit file

Unstaged files are not necessarily "untracked". Even though you mentioned "modified files" which means they are being tracked, you actually missed that part in your illustration (quoted above). Please correct that.

Also, if you are using a new word, you should be explaining it up a bit as well. In this case, the words staging and staging area. Please write short explanations of these terms.

> Ignored Files

This also is an unexplained term. Write out a brief explanation about ignored files, what they are, why would someone ignore files, what kind of files should be ignored, and give a couple of examples.

> Removing files from staging area

Although I know if you start writing about `git reset` its advantages and disadvantages, the article could be really lengthy, right now, this section doesn't do a very good job in telling if there could be any disadvantages of using `git reset`. Either briefly add that if you feel there are any disadvantages that the reader should be aware of, or at least provide a link to read about `git reset`. (P.S. if any of the students write about `git reset` we will update the link, later on, to point to that article instead, but you should add a working link to some other site for now)

> Examples

This entire section has only one or two good examples. I am not stopping you from adding examples of `git status` but examples of `git reset` are unnecessary. Instead, provide more examples of `git add`. Add complexity to your examples by introducing more flags and combining flags (if there is a possibility to combine). Right now, I would say the example section is a little weak.

> Details

Well, this is optional, but if you can, then add more details. The current paragraph seems coming out of the blue with no real introduction to `index` and why Git maintains it. This could also be a little confusing so if you want to skip it, you may, but then add something tangible in replacement to removing this paragraph.

**Comment by aashishnagpal** [comment]
@plosty Phil, did you miss the last communication I sent to you? There's a review in my last comment. Let me know when can you complete the improvements?

**Comment by plosty** [comment]
@aashishnagpal  - I'm really sorry for the delay, I'l try to get this finished for you tomorrow.

**Comment by plosty** [comment]
@aashishnagpal - I'm sorry for the delay in finishing this work. I updated the file from your feedback, can you review and see if this meets the required standard? (Many thanks for your detailed feedback).

Regards

Phil

cc @NathanJPlummer

**Pull request merged**
