### PR TITLE
Brian otieno git commit contribution

### PR DESCRIPTION
**Pull request by jumaxbrian**
I have written a clear, easy-to-comprehend details for git-commit. I believe this explanation, free of complex technical terms, will swiftly and thoroughly inform anyone about the use-cases, merit, and advantages, 
of git-commit. Seasoned developers, new programmers, and even amateur users new to git will benefit from the clear language, exposing the usage of the command to a broader range of users.

### CODE REVIEW

**Comment by aashishnagpal** [comment]
@jumaxbrian 

Hey, Brian.

Thank you for your submission. We appreciate you stepping up and taking `git commit` to explain to the masses.

Your submission is okay. Below are a few points to consider for improvement, to take it to another level.

- You have used hyphenated `git-commit` instead of `git commit` at some places. Please correct this.

- You added below two paragraphs into _Description_

  > Git is a distributed version control system. It simply means more than one person can work on a single file at the same time. However, in order for any version control system to work, we need to have a way of indicating/marking/creating these various versions of a file. This is where a commit becomes useful.

  > A commit is the mechanism used to mark a specific point as a point of reference.In Git, a commit is a snapshot of the git repository at that particular point in time. The snapshot being the entire contents of every file in the repository. But how do we create a commit?

  You can move these two paragraphs into _Introduction_ itself. Right now the _Introduction_ is quite small.

-  > It simply means more than one person can work on a single file at the same time.

   This is not the simple meaning of being a Distributed Version Control System. In a Non-Distributed Version Control System also, you can have multiple contributors working on a single file at the same time. **Either update this sentence with the correct meaning of DVCS or remove this.**

-  > A commit is the mechanism used to mark a specific point as a point of reference.

   This is a bit vague. Please update to make it clearer.

-  > The snapshot being the entire contents of every file in the repository.

   Again, a snapshot is not exactly the _entire contents of every file in the repository_. It is just a representative of the difference of the changes made. **Please update this sentence with the correct explanation.**

- > git commit -m "commit message" - performs a commit with the value in quotes as the commit message. You should edit it to be meaningful to you.

  Add the plain simple `git commit` without `-m` flag in the _Usage_ section prior to this quoted line. Also, the commit message should not only be meaningful to the person who is committing but also to the entire team so that everyone on the team understands what changes are there in the commit. **Please update this.**

- > git commit -e [--file=<file>| -m <msg> ] - performs a commit while allowing you to edit the messages taken from the various sources e.g. file <file>, commit message <msg>.

  This is not very clear. Could you explain this a bit more?

- > ```
  > touch file1 file2 file3
  > git add .
  > git commit file1
  > ```
  > This will only commit file1 while leaving the other changes eg. file2 and file3 in the staging area. Thus, it allows you to commit only certain changes from the staging area.

  There is no natural progrssion in the _Usage_ section and thus a bit difficult to understand. Especially this parted (quoted). It seems out of place.

- > git commit - is preferred to commiting using the -m option. This is because it allows you to write your commit in the default editor that is started. Thus it gives you the opportunity to write better commits which would be more meaningful to you later especially when you find yourself in a fix and would really want to know the exact changes you made in each commit. Usually, it is preferred to write a small summary of about 50 characters or less. Thereafter, you skip one line then list all the changes that are taking place in that commit. The commit is performed when you save and close the editor.

  Did you mean, "is preferred to committing **without** using the `-m` option"? The explanation is for **without** the flag but you did not mention that. Also, as I mentioned earlier, take this paragraph to the starting of the usage section along with the explanation of `git commit` without the `-m` flag.

---

Overall a good effort.

Send me a reply here once you have completed the suggested improvements. I will mark the assignment complete after that.

**Comment by NathanJPlummer** [comment]
@jumaxbrian 

How are things going with this assignment?

**Comment by jumaxbrian** [comment]
@nathan_plummer

Done.

On Sat, Aug 26, 2017 at 11:27 PM, Nathan J Plummer <notifications@github.com

**Comment by aashishnagpal** [comment]
@jumaxbrian Have you completed this part? Have you added the suggested improvements? If you did, did you forget to commit and push any changes to this repository?

@NathanJPlummer As you can see, there are just the initial 11 commits and no commit thereafter. If there had been any new commits after the feedback they would have shown separately.

**Comment by jumaxbrian** [comment]
@aashishnagpal 

Hi Aashish,

I added the changes and committed to the other repository, but I forgot to do so in this one. I have now committed the changes and you can have a look at them.

**Pull request merged**
